[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:xvfb]
command=/usr/bin/Xvfb :1 -screen 0 %(ENV_DISPLAY_WIDTH)sx%(ENV_DISPLAY_HEIGHT)sx24
autorestart=true
stdout_logfile=/var/log/xvfb.log
stderr_logfile=/var/log/xvfb_err.log
priority=10

[program:fluxbox]
command=/usr/bin/fluxbox -display :1
autorestart=true
stdout_logfile=/var/log/fluxbox.log
stderr_logfile=/var/log/fluxbox_err.log
priority=20
environment=DISPLAY=":1"

[program:x11vnc]
command=/usr/bin/x11vnc -display :1 -forever -shared -rfbauth /root/.vnc/passwd -rfbport 5900
autorestart=true
stdout_logfile=/var/log/x11vnc.log
stderr_logfile=/var/log/x11vnc_err.log
priority=30
environment=DISPLAY=":1"
